version: '3'
services:
  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB-postgres}
      POSTGRES_USER: ${POSTGRES_USER-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}

  web:
    restart: always
    build:
      context: ../star-burger/
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - media:/app/media
    depends_on:
      - db

volumes:
  db_data:
  media:
