# Generated by Django 3.2 on 2022-07-27 11:31

from django.db import migrations, models
import django.db.models.deletion
import foodcartapp.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(default=foodcartapp.models.order_mum_default, max_length=255, verbose_name='Номер заказа')),
                ('first_name', models.CharField(db_index=True, max_length=255, verbose_name='Имя заказчика')),
                ('last_name', models.CharField(db_index=True, max_length=255, verbose_name='Фамилия заказчика')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Телефон')),
                ('delivery_address', models.TextField(verbose_name='Адрес заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_num', models.IntegerField(default=1, verbose_name='Номер позиции')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество, шт.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.product', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Позиции заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
    ]
