# Generated by Django 3.2 on 2022-09-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20220915_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlines',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена'),
        ),
    ]
