# Generated by Django 3.2 on 2022-09-16 10:35

from django.db import migrations


def calculate_orders_price_positions(apps, shema_editor):
    OrderLines = apps.get_model('foodcartapp', 'OrderLines')
    for order in OrderLines.objects.iterator():
        order.price = order.product.price
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderlines_price'),
    ]

    operations = [
        migrations.RunPython(calculate_orders_price_positions),
    ]
