# Generated by Django 3.2 on 2022-09-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20220916_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cashless', 'По карте при оформлении'), ('cash', 'Наличными при доставке')], db_index=True, default='cashless', max_length=12, verbose_name='Тип оплаты'),
        ),
    ]
